export const copy = {
  units: {
    seconds: "초",
  },
  app: {
    eyebrow: "피하기 프로젝트",
    title: "똥 피하기",
    subtitle: "로그인 후 바로 시작",
    sessionSaves: (count: number) => `이번 실행에서 저장한 기록 ${count}개`,
    guest: "게스트",
    online: "온라인",
    screens: {
      auth: "접속 화면",
      menu: "메인 홈",
      game: "실전 플레이",
      results: "결과 확인",
      records: "기록 보관함",
    },
    screenSubtitle: {
      auth: "계정 접속",
      menu: "모드 선택",
      game: "실전 플레이",
      results: "결과 확인",
      records: "기록 확인",
    },
  },
  auth: {
    title: "똥 피하기",
    subtitle: "계정으로 접속",
    switchToLogin: "로그인으로 전환",
    switchToSignup: "회원가입으로 전환",
    modeSignup: "회원가입",
    modeLogin: "로그인",
    username: "아이디",
    password: "비밀번호",
    signup: "계정 만들기",
    login: "로그인",
    consoleTitle: "접속",
    consoleDescription: "기록은 계정별 저장",
    featureRounds: "라운드 + 보스",
    featureSave: "결과 저장",
    featureItems: "아이템 5종",
  },
  menu: {
    welcome: (username: string) => `${username} 님, 준비됐나요?`,
    subtitle: "모드를 고르세요.",
    heroLine: "피하고, 모으고, 버텨라",
    heroBadge: "픽셀 아레나",
    start: "게임 시작",
    chooseSingle: "싱글",
    chooseMulti: "멀티",
    modeLabel: "선택 모드",
    modeShort: {
      normal: "일반",
      hard: "하드",
    },
    modeBanner: {
      normal: "일반 모드",
      hard: "하드 모드",
    },
    records: "랭킹 보기",
    logout: "로그아웃",
    normalSummary: "완만한 웨이브와 짧은 보스",
    hardSummary: "더 빠른 낙하와 긴 보스",
    profile: "파일럿",
    saveCount: "이번 실행 저장",
    storage: "기록 저장",
    storageReady: "연동 완료",
  },
  game: {
    mode: "모드",
    round: "라운드",
    lives: "하트",
    score: "점수",
    wave: "일반 구간",
    boss: "보스 구간",
    leave: "게임 나가기",
    transitionPrefix: "경고",
    modeLabel: {
      normal: "일반",
      hard: "하드",
    },
    itemLegend: {
      invincibility: "무적",
      speed: "가속",
      heal: "회복",
      slow: "슬로우",
      clear: "정리",
    },
    controlsValue: "좌우 이동",
    left: "왼쪽",
    right: "오른쪽",
    itemToast: {
      invincibility: "무적 4초",
      speed: "가속 4초",
      heal: "하트 +1",
      slow: "슬로우 4초",
      clear: "화면 정리",
    },
    alerts: {
      lifeLost: (lives: number) => (lives > 0 ? `피격! 하트 ${lives}` : "하트 소진"),
      lifeRecovered: "하트 +1",
      roundRecovered: "라운드 보너스 하트 +1",
      invincibilityEnded: "무적 종료",
      speedEnded: "가속 종료",
      slowEnded: "슬로우 종료",
      bossIncoming: "보스 경고",
      bossCleared: "보스 돌파",
      gameOver: "게임 오버",
    },
    effectLabel: {
      invincibility: "무적",
      speed: "가속",
      slow: "슬로우",
    },
    activeEffects: "활성 효과",
    bossAttack: "보스 공격",
  },
  results: {
    cleared: "최고 기록",
    failed: "게임 오버",
    modeNormal: "일반 모드",
    modeHard: "하드 모드",
    roundLabel: (round: number) => `${round}라운드 도달`,
    score: "점수",
    time: "생존 시간",
    saved: "저장 상태",
    savedYes: "저장 완료",
    savedSaving: "저장 중",
    savedPending: "재시도 대기",
    retrySave: "다시 저장",
    saving: "저장 중...",
    savedButton: "저장 완료",
    viewRecords: "기록 보기",
    backToMenu: "메뉴로",
    retry: "다시 도전",
    outcomeClear: "클리어",
    outcomeFail: "게임 오버",
    summaryTitle: "결과 요약",
    savePanel: "기록 저장 상태",
  },
  records: {
    title: "랭킹 & 전적",
    badge: "랭킹",
    meta: "내 전적과 실제 플레이어 랭킹",
    back: "뒤로",
    best: "최고 기록",
    recent: "최근 기록",
    normal: "일반",
    hard: "하드",
    none: "기록 없음",
    loading: "기록을 불러오는 중...",
    roundEntry: (score: number, round: number) => `점수 ${score} / ${round}라운드`,
    normalBest: "일반 최고 점수",
    hardBest: "하드 최고 점수",
    totalRuns: "총 싱글 플레이",
    totalClears: "클리어 수",
    recentLog: "최근 싱글 전적",
    playerRanking: "실제 플레이어 랭킹",
    multiplayerBest: "멀티 최고 순위",
    multiplayerWins: "멀티 승리 수",
    multiplayerMatches: "멀티 경기 수",
    multiplayerRecent: "멀티 최근 전적",
    placementEntry: (placement: number, totalPlayers: number, reachedRound: number) => `${placement}등 / ${totalPlayers}명 / ${reachedRound}라운드`,
  },
  multiplayer: {
    entry: '멀티',
    homeTitle: '멀티 대전',
    quickJoin: '빠른 입장',
    createRoom: '방 만들기',
    joinByCode: '방 코드 입장',
    roomCode: '방 코드',
    lobbyTitle: '대기방',
    ready: '준비',
    cancelReady: '준비 해제',
    start: '시작',
    leave: '나가기',
    options: '방 옵션',
    difficulty: '난이도',
    bodyBlock: '길막',
    visibility: '방 공개',
    publicRoom: '공개방',
    privateRoom: '비공개방',
    createRoomSetup: '방 만들기 설정',
    quickJoinHint: '아무 공개방에 바로 입장합니다',
    createRoomHint: '공개/비공개와 룰을 정한 뒤 방을 만듭니다',
    debuffTier: '디버프 강도',
    spectator: '관전 중',
    reconnecting: '재접속 대기',
    finished: '종료',
    remainingPlayers: '남은 인원',
    players: '플레이어',
    waitingRoom: '대기 중',
    inGame: '게임 진행 중',
    joinPlaceholder: '예: ABC123',
    statusConnecting: '연결 중...',
    statusConnected: '연결됨',
    startHint: '방장만 시작할 수 있습니다',
    startNeedPlayers: '2명 이상 있어야 시작 가능',
    startNeedReady: '전원이 준비해야 시작 가능',
    difficultyNormal: '일반',
    difficultyHard: '하드',
    chat: '채팅',
    sendChat: '보내기',
    jumpHint: '부딪힘 ON일 때 점프로 통과 가능',
    debuffActive: '현재 디버프',
    debuffLabels: {
      slow: '이동 둔화',
      reverse: '좌우 반전',
      input_delay: '입력 지연',
      vision_jam: '시야 방해',
      item_lock: '아이템 봉인',
    },
  },
  transitions: {
    bossIncoming: "보스 패턴이 시작됩니다",
    bossCleared: "보스 패턴 종료, 다음 웨이브로 이동합니다",
    nextRound: (round: number) => `${round}라운드 시작`,
  },
} as const;

export function formatSecondsLabel(value: number) {
  return `${value.toFixed(1)}${copy.units.seconds}`;
}

const errorTranslations: Record<string, string> = {
  "Username is already taken.": "이미 사용 중인 아이디입니다.",
  "Invalid username or password.": "아이디 또는 비밀번호가 올바르지 않습니다.",
  "Authentication required.": "로그인이 필요한 화면입니다.",
  "No active session.": "로그인 세션이 없습니다.",
  "Request failed": "요청 처리에 실패했습니다.",
  "Failed to load records": "기록을 불러오지 못했습니다.",
  "Failed to save result": "결과 저장에 실패했습니다.",
};

export function translateErrorMessage(message: string) {
  return errorTranslations[message] ?? message;
}
